config/routes.rb
Rails.application.routes.draw do

  if Settings.multitenancy.enabled
    constraints host: Account.admin_host do
      get '/account/sign_up' => 'account_sign_up#new', as: 'new_sign_up'
      post '/account/sign_up' => 'account_sign_up#create'
      get '/', to: 'splash#index'

      # pending https://github.com/projecthydra-labs/hyrax/issues/376
      get '/dashboard', to: redirect('/')

      namespace :proprietor do
        resources :accounts
      end
    end
  end

  get 'status', to: 'status#index'

  mount BrowseEverything::Engine => '/browse'
  resource :site, only: [:update] do
    resources :roles, only: [:index, :update]
    resource :labels, only: [:edit, :update]
  end

  root 'hyrax/homepage#index'

  devise_for :users, controllers: { invitations: 'hyku/invitations', registrations: 'hyku/registrations' }
  mount Qa::Engine => '/authorities'

  mount Blacklight::Engine => '/'
  mount Hyrax::Engine, at: '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  curation_concerns_basic_routes do
    member do
      get :manifest
    end
  end

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  namespace :admin do
    resource :account, only: [:edit, :update]
    resources :users, only: [:destroy]
    resources :groups do
      member do
        get :remove
      end

      resources :users, only: [:index], controller: 'group_users' do
        collection do
          post :add
          delete :remove
        end
      end
    end
  end

  mount Peek::Railtie => '/peek'
  mount Riiif::Engine => '/images', as: 'riiif'
end

app/models/hyku/group.rb
module Hyku
  class Group < ApplicationRecord
    self.table_name = 'hyku_groups'

    resourcify # Declares Hyku::Group a resource model so rolify can manage membership

    MEMBERSHIP_ROLE = :member
    DEFAULT_MEMBER_CLASS = User

    validates :name, presence: true

    def self.search(query)
      if query.present?
        where("name LIKE :q OR description LIKE :q", q: "%#{query}%")
      else
        all
      end
    end

    def search_members(query, member_class: DEFAULT_MEMBER_CLASS)
      if query.present? && member_class == DEFAULT_MEMBER_CLASS
        members.where("email LIKE :q OR display_name LIKE :q", q: "%#{query}%")
      else
        members(member_class: member_class)
      end
    end

    def add_members_by_id(ids, member_class: DEFAULT_MEMBER_CLASS)
      new_members = member_class.find(ids)
      Array.wrap(new_members).collect { |m| m.add_role(MEMBERSHIP_ROLE, self) }
    end

    def remove_members_by_id(ids, member_class: DEFAULT_MEMBER_CLASS)
      old_members = member_class.find(ids)
      Array.wrap(old_members).collect { |m| m.remove_role(MEMBERSHIP_ROLE, self) }
    end

    def members(member_class: DEFAULT_MEMBER_CLASS)
      member_class.with_role(MEMBERSHIP_ROLE, self)
    end

    def number_of_users
      members.count
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify

  scope :site, -> { where(resource_type: "Site") }
end

app/controllers/admin/groups_controller.rb
module Admin
  class GroupsController < AdminController
    before_action :load_group, only: %i[edit update remove destroy]

    # rubocop:disable Metrics/AbcSize
    def index
      add_breadcrumb t(:'hyrax.controls.home'), root_path
      add_breadcrumb t(:'hyrax.dashboard.breadcrumbs.admin'), hyrax.dashboard_path
      add_breadcrumb t(:'hyku.admin.groups.title.index'), admin_groups_path
      @groups = Hyku::Group.search(params[:q]).page(page_number).per(page_size)
    end
    # rubocop:enable Metrics/AbcSize

    def new
      add_breadcrumb t(:'hyrax.controls.home'), root_path
      add_breadcrumb t(:'hyrax.dashboard.breadcrumbs.admin'), hyrax.dashboard_path
      add_breadcrumb t(:'hyku.admin.groups.title.new'), new_admin_group_path
      @group = Hyku::Group.new
    end

    def create
      new_group = Hyku::Group.new(group_params)
      if new_group.save
        redirect_to admin_groups_path, notice: t('hyku.admin.groups.flash.create.success', group: new_group.name)
      elsif new_group.invalid?
        redirect_to new_admin_group_path, alert: t('hyku.admin.groups.flash.create.invalid')
      else
        redirect_to new_admin_group_path, flash: { error: t('hyku.admin.groups.flash.create.failure') }
      end
    end

    def edit
      add_breadcrumb t(:'hyrax.controls.home'), root_path
      add_breadcrumb t(:'hyrax.dashboard.breadcrumbs.admin'), hyrax.dashboard_path
      add_breadcrumb t(:'hyku.admin.groups.title.edit'), edit_admin_group_path
    end

    def update
      if @group.update(group_params)
        redirect_to admin_groups_path, notice: t('hyku.admin.groups.flash.update.success', group: @group.name)
      else
        redirect_to edit_admin_group_path(@group), flash: {
          error: t('hyku.admin.groups.flash.update.failure', group: @group.name)
        }
      end
    end

    def remove
      add_breadcrumb t(:'hyrax.controls.home'), root_path
      add_breadcrumb t(:'hyrax.dashboard.breadcrumbs.admin'), hyrax.dashboard_path
      add_breadcrumb t(:'hyku.admin.groups.title.edit'), edit_admin_group_path
      add_breadcrumb t(:'hyku.admin.groups.title.remove'), request.path
    end

    def destroy
      if @group.destroy
        redirect_to admin_groups_path, notice: t('hyku.admin.groups.flash.destroy.success', group: @group.name)
      else
        logger.error("Hyku::Group id:#{@group.id} could not be destroyed")
        redirect_to admin_groups_path flash: { error: t('hyku.admin.groups.flash.destroy.failure', group: @group.name) }
      end
    end

    private

      def load_group
        @group = Hyku::Group.find_by(id: params[:id])
      end

      def group_params
        params.require(:hyku_group).permit(:name, :description)
      end

      def page_number
        params.fetch(:page, 1).to_i
      end

      def page_size
        params.fetch(:per, 10).to_i
      end
  end
end

app/views/admin/groups/_form.html.erb
<%
  if @group.new_record?
    target_path = admin_groups_path
  else
    target_path = admin_group_path(@group)
  end
%>
<div class="panel panel-default">
  <%= simple_form_for @group, url: target_path do |f| %>
    <div class="panel-body">
      <%= f.input :name %>
      <%= f.input :description, as: :text %>
    </div>
    <div class="panel-footer text-right">
      <%= link_to t('simple_form.cancel'), admin_groups_path, class: 'btn btn-link action-cancel' %>
      <%= f.submit class: 'btn btn-primary action-save' %>
    </div>
  <% end %>
</div>

app/views/admin/groups/_nav.html.erb
<%# NOTE: The #new action does not use this navigation partial. %>
<div class="panel-tab-wrapper">
  <ul class="nav nav-tabs">
    <% navigation_presenter.tabs.each do |tab| %>
      <%= content_tag :li, role: 'presentation', class: tab.css_class do %>
        <%= link_to tab.name, tab.path %>
      <% end %>
    <% end %>
  </ul>
  <%= link_to t('hyku.admin.groups.nav.index'), admin_groups_path, class: 'pull-right nav-escape-link' %>
</div>

app/views/admin/groups/_per_page.html.erb
<%= simple_form_for :page_size, url: @target, method: :get, html: { class: 'form-inline js-per-page' } do |f| %>
  <% if params[:q].present? %>
    <%= f.input :q, as: :hidden, input_html: { name: :q, value: params[:q] } %>
  <% end %>
  <% if params[:page].present? %>
    <%= f.input :page, as: :hidden, input_html: { name: :page, value: params[:page] } %>
  <% end %>
  <%= f.input :per, collection: [10, 25, 100], include_blank: false, required: false, selected: params[:per], input_html: { class: 'js-per-page__select', name: :per } %>
  <%= t('hyku.admin.groups.label.per_page') %>
  <%= f.submit class: 'btn btn-default js-per-page__submit' %>
<% end %>

app/views/admin/groups/_search.html.erb
<%= simple_form_for :group_search, method: :get, html: { class: 'form-inline list-scope' } do |f| %>
  <% if params[:per].present? %>
    <%= f.input :per, as: :hidden, input_html: { name: :per, value: params[:per] } %>
  <% end %>
  <% if params[:page].present? %>
    <%= f.input :page, as: :hidden, input_html: { name: :page, value: params[:page] } %>
  <% end %>
  <div class="form-group list-scope">
    <%= f.input :q, required: false, input_html: { class: 'list-scope__query', name: :q, value: params[:q] }, wrapper_html: { class: 'list-scope__query-wrapper'} %>
    <% if params[:q].present? %>
      <%= link_to content_tag(:span, '&times;'.html_safe, :'aria-hidden' => true),  @target, class: 'close list-scope__reset', :'aria-label' => t('hyku.admin.groups.action.search.clear') %>
    <% end %>
  </div>
  <%= f.submit class: 'btn btn-primary list-scope__submit' %>
<% end %>

app/views/admin/groups/edit.html.erb
<% content_for :page_title, construct_page_title(t('hyku.admin.groups.title.edit'), t('hyku.admin.title')) %>
<% provide :page_header do %>
  <h1>
    <span class="fa fa-users"></span>
    <%= t('hyku.admin.groups.title.edit') %>
  </h1>
<% end %>
<%= render 'nav' %>
<%= render 'form' %>

app/views/admin/groups/index.html.erb
<% content_for :page_title, construct_page_title(t('hyku.admin.groups.title.index'), t('hyku.admin.title')) %>
<% provide :page_header do %>
  <h1>
    <span class="fa fa-users"></span>
    <%= t('hyku.admin.groups.title.index') %>
  </h1>
<% end %>

<div class="panel panel-default group-listing">
  <div class="panel-heading">
    <% group_count = Hyku::Group.all.count %>
    <% if group_count == 1 %>
      <%= t('hyku.admin.groups.describe_singular_quantity_html') %>
    <% else %>
      <%= t('hyku.admin.groups.describe_quantity_html', number: group_count ) %>
    <% end %>
    <%= link_to t('hyku.admin.groups.action.create'), new_admin_group_path, class: 'btn btn-primary pull-right new-group' %>
  </div>
  <div class="panel-body">
    <div class="container-fluid full-width-container">
      <div class="row">
        <div class="col-sm-6">
          <%= render 'per_page', target: admin_groups_path %>
        </div>
        <div class="col-sm-6 text-right">
          <%= render 'search', target: admin_groups_path %>
        </div>
      </div>
    </div>

    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th><%= t('hyku.admin.groups.label.name') %></th>
            <th><%= t('hyku.admin.groups.label.members') %></th>
            <th><%= t('hyku.admin.groups.label.created_at') %></th>
            <th><%= t('hyku.admin.groups.label.actions') %></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td>
                <b><%= group.name %></b>
                <% if group.description.present? %>
                  <p class="help-block">
                  <%= group.description %>
                  </p>
                <% end %>
              </td>
              <td>
                <%= group.number_of_users %>
              </td>
              <td>
                <%= group.created_at.to_date.to_formatted_s(:standard) %>
              </td>
              <td>
                <%= link_to t('hyku.admin.groups.action.edit'), edit_admin_group_path(group), class: 'btn btn-default' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <nav class="pull-right">
      <%= paginate @groups %>
    </nav>
  </div>
</div>

app/views/admin/groups/new.html.erb
<% content_for :page_title, construct_page_title(t('hyku.admin.groups.title.new'), t('hyku.admin.title')) %>
<% provide :page_header do %>
  <h1>
    <span class="fa fa-users"></span>
    <%= t('hyku.admin.groups.title.new') %>
  </h1>
<% end %>
<div class="panel-tab-wrapper">
  <ul class="nav nav-tabs">
    <li role="presentation" class="active">
      <a href="javascript:void(0);"><%= t('hyku.admin.groups.nav.attributes') %></a>
    </li>
    <li role="presentation" class="disabled">
      <a href="javascript:void(0);"><%= t('hyku.admin.groups.nav.members') %></a>
    </li>
    <li role="presentation" class="disabled">
      <a href="javascript:void(0);"><%= t('hyku.admin.groups.nav.delete') %></a>
    </li>
  </ul>
  <%= link_to t('hyku.admin.groups.nav.index'), admin_groups_path, class: 'pull-right nav-escape-link' %>
</div>
<%= render 'form' %>

app/views/admin/groups/remove.html.erb
<% content_for :page_title, construct_page_title(t('hyku.admin.groups.title.edit'), t('hyku.admin.title')) %>
<% provide :page_header do %>
  <h1>
    <span class="fa fa-users"></span>
    <%= t('hyku.admin.groups.title.edit') %>
  </h1>
<% end %>

<%= render 'nav' %>
<div class="panel panel-default">
  <div class="panel-body">
    <blockquote class="callout callout-danger callout-with-action">
      <h3><%= t('hyku.admin.groups.title.delete', group: @group.name) %></h3>
      <p>
      <%= t('hyku.admin.groups.action.remove.description') %>
      </p>
      <div class="callout-action">
        <%= link_to t('hyku.admin.groups.action.remove.submit'),  admin_group_path(@group), class: 'btn btn-danger action-delete', method: :delete, data: { confirm: t('hyku.admin.groups.action.remove.confirmation') } %>
      </div>
    </blockquote>
  </div>
</div>

app/views/admin/groups/users.html.erb
<% content_for :page_title, construct_page_title(t('hyku.admin.groups.title.edit'), t('hyku.admin.title')) %>
<% provide :page_header do %>
  <h1>
    <span class="fa fa-users"></span>
    <%= t('hyku.admin.groups.title.edit') %>
  </h1>
<% end %>

<%= render '/admin/groups/nav' %>
<div class="panel panel-default group-user-listing">
  <div class="panel-body">

    <p class="lead"><%= t('hyku.admin.groups.action.members.description') %></p>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t('hyku.admin.groups.title.add_user') %></h3>
      </div>
      <div class="panel-body">
        <%= simple_form_for :user_search, url: hyrax.users_path, method: :get, html: { class: 'form-inline pull-left js-group-user-search' } do |f| %>
          <%= f.input :uq, name: :uq, required: false, input_html: { class: 'js-group-user-search__query', value: params[:uq] } %>
          <%= f.submit class: 'btn btn-default js-group-user-search__submit' %>
        <% end %>

        <%= simple_form_for :add_user_to_group, url: add_admin_group_users_path(group_id: @group.to_param), html: { class: 'form-inline pull-left js-group-user-add' } do |f| %>
          <%= f.input :user_ids, required: false, input_html: { class: 'js-group-user-add__id', name: :user_ids } %>
          <%= f.submit class: 'btn btn-primary js-group-user-add__submit' %>
        <% end %>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t('hyku.admin.groups.title.list_members') %></h3>
      </div>
      <div class="panel-body">
        <div class="container-fluid full-width-container">
          <div class="row">
            <div class="col-sm-6">
              <%= render '/admin/groups/per_page', target: admin_group_users_path %>
            </div>
            <div class="col-sm-6 text-right">
              <%= render '/admin/groups/search', target: admin_group_users_path %>
            </div>
          </div>
        </div>

        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= t('hyku.users.label.name') %></th>
                <th><%= t('hyku.users.label.user_key') %></th>
                <th><%= t('hyku.users.label.date_joined') %></th>
                <th><%= t('hyku.users.label.last_login') %></th>
                <th><%= t('hyku.admin.groups.label.actions') %></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <%= user.name %>
                  </td>
                  <td>
                    <%= user.user_key %>
                  </td>
                  <td>
                    <%= user.created_at.to_date.to_formatted_s(:standard) %>
                  </td>
                  <td>
                    <%= user.updated_at.to_date.to_formatted_s(:standard) %>
                  </td>
                  <td>
                    <%= simple_form_for :revoke_membership, url: remove_admin_group_users_path(group_id: @group.to_param), method: :delete, html: { class: 'form' } do |f| %>
                      <%= f.input :user_ids, as: :hidden, input_html: { name: :user_ids, value: user.id } %>
                      <%= f.submit class: 'btn btn-danger' %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <nav class="pull-right">
          <%= paginate @users %>
        </nav>
      </div>
    </div>
  </div>
</div>